feat support invite private to private network
jambonz/sbc-outbound pull request #111
Opened 2023-11-12 13:36 UTC by xquanluu

2023-11-13 20:27 UTC, davehorton requested changes

2023-11-13 20:27 UTC, davehorton commented on lib/call-session.js
> +          private_network: contact.includes('transport=ws') ? false : await isPrivateVoipNetwork(destUri),
why await?  That function isPrivateVoipNetwork does not appear to be async

2023-11-13 20:27 UTC, davehorton commented on lib/utils.js
> +        const matcher = new CIDRMatcher(process.env.PRIVATE_VOIP_NETWORK_CIDR.split(','));
this CIDRMatcher object is always going to be created with the same network CIDR.  Can we just create it once when the file is included?

2023-11-14 13:03 UTC, davehorton commented on lib/call-session.js
> +          private_network: contact.includes('transport=ws') ? false : await isPrivateVoipNetwork(destUri),
@xquanluu ??

2023-11-27 13:06 UTC, vdharashive commented
it is working Please merge this PR

2023-11-27 13:26 UTC, davehorton approved these changes

2023-11-27 13:26 UTC, merged